Blog/Controllers/NewArticleController.cs
using Blog.Models;
using System;
using System.Web.Mvc;

namespace Blog.Controllers
{
	public class NewArticleController : Controller
    {
        [HttpGet]
        public ViewResult Create()
        {
			DataBaseCategories dataBaseCategory = new DataBaseCategories();
			NewArticle newArticle = new NewArticle
			{
				Categories = new SelectList(dataBaseCategory.Select(), "Category_Id", "Name")
			};
			return View(newArticle);
        }

		[HttpPost]
		public ActionResult Create(NewArticle newArticle)
		{
			DataBaseTegs dataBaseTeg = new DataBaseTegs();
			DataBaseArticles dataBaseArticles = new DataBaseArticles();
			DataBaseArticles_Tegs dataBaseArticles_Tegs = new DataBaseArticles_Tegs(); 

			newArticle.Article.Category_Id = newArticle.CategoryId;
			newArticle.Article.DateTime = DateTime.Now;
			int id_article = dataBaseArticles.Insert(newArticle.Article);

			string[] tegs = newArticle.Tegs.Split(new char[] { '#' }, StringSplitOptions.RemoveEmptyEntries);

			foreach (string teg in tegs)
			{
				int id_teg = dataBaseTeg.Insert("#" + teg);
				dataBaseArticles_Tegs.Insert(id_article, id_teg);
			}

			DataBaseCategories dataBaseCategory = new DataBaseCategories();
			NewArticle newArticle1 = new NewArticle
			{
				Categories = new SelectList(dataBaseCategory.Select(), "Category_Id", "Name")
			};

			return RedirectToAction("Index", "Home");
		}
    }
}

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – Blog.com</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
				<div class="navbar-brand">Блог</div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("Категории", "Categories", "Categories")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
					@{ 
						if (HttpContext.Current.User.Identity.IsAuthenticated)
						{
						<li>@Html.ActionLink("Опубликовать статью", "Create", "NewArticle")</li>
						}
					}
					<li>
						@{
							if (HttpContext.Current.User.Identity.IsAuthenticated)
							{
								@Html.ActionLink("Личный кабинет", "Admin", "Account")
							}
							else
							{
								@Html.ActionLink("Войти", "Login", "Account")

							}
						}
					</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – Blog.com</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>